language: r
dist: bionic
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/ribir
  - richelbilderbeek/mcbette
  - richelbilderbeek/becosys
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/raket@richel
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi


script:
  - ./scripts/1_install_raket
  - ./scripts/2_create_input_files_general
  # - ./scripts/2_create_input_files_sampling
  #- ./scripts/3_run_raket

after_success:
  - pwd
  - cd data; find .

after_failure:
  - pwd
  - cd data; find .
