language: r
dist: bionic
cache: packages

r_github_packages:
  - Giappo/mbd
  - richelbilderbeek/ribir
  - richelbilderbeek/mcbette
  - richelbilderbeek/becosys
  - thijsjanzen/nodeSub
  - richelbilderbeek/pirouette
  - richelbilderbeek/peregrine
  - richelbilderbeek/raket
  - rsetienne/PBD/PBD

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi


script:
  - ./scripts/1_install_raket
  - ./scripts/2_create_input_files_test
  - travis_wait 60 ./scripts/3_run_raket
  - ./scripts/7_create_nltt_stats_file.sh
  - ./scripts/8_create_esses_files.sh
  - ./scripts/9_create_marg_liks_file.sh
  - ./scripts/11_create_n_taxa_file.sh

after_success:
  - pwd
  - cd data; find . ; cd ..
  - cd result ; find . ; cd ..

after_failure:
  - pwd
  - cd data; find . ; cd ..
  - cd result ; find . ; cd ..
