language: r
dist: xenial
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - ropensci/beautier@develop
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/ribir
  - richelbilderbeek/mcbette
  - richelbilderbeek/becosys
  #- richelbilderbeek/PBD/PBD # Bleeding-edge version
  - richelbilderbeek/pirouette@richel
  - richelbilderbeek/raket@develop
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling
  # - xl0418/dododo

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

script:
  - ./scripts/1_install_raket
  - #./scripts/2_create_input_files_general
  - #./scripts/3_create_posterior_files
  - #./scripts/4_create_nltt_files
  - #./scripts/5_nltt_files_to_csv
  - #./scripts/6_to_long
  - #./scripts/7_create_fig_1

after_success:
  - pwd
  - cd data; find .

after_failure:
  - pwd
  - cd data; find .
