language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - hunspell
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/becosys
  - richelbilderbeek/mauricer
  - richelbilderbeek/PBD/PBD # Bleeding-edge version
  - richelbilderbeek/pirouette
  - richelbilderbeek/raket
  - richelbilderbeek/tracerer
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

script:
  - ./scripts/create_input_files_general
  # Java
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./scripts/1_install_raket
  - ./scripts/2_create_input_files_general
  - ./scripts/3_create_output_files
  - ./scripts/4_create_nltt_files
  - ./scripts/5_nltt_files_to_csv
  - ./scripts/6_to_long
  - ./scripts/7_create_fig_1

after_success:
  - pwd
  - cd data; find .

after_failure:
  - pwd
  - cd data; find .
