#!/bin/bash
# Script to install razzo and its dependencies
# on the Peregrine computer cluster
#
# Usage, locally:
#
#   ./scripts/1_install_raket
#
# Usage, on Peregrine:
#
#   sbatch ./scripts/1_install_raket
#
# Peregrine directives:
#SBATCH --partition=gelifes
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=1_install_raket
#SBATCH --output=1_install_raket.log
module load R
Rscript -e 'devtools::install_github("ropensci/beautier")'
Rscript -e 'devtools::install_github("ropensci/tracerer")'
Rscript -e 'devtools::install_github("ropensci/beastier")'
Rscript -e 'devtools::install_github("ropensci/mauricer")'
Rscript -e 'devtools::install_github("ropensci/babette")'
Rscript -e 'devtools::install_github("richelbilderbeek/PBD/PBD", ref = "master")'
Rscript -e 'devtools::install_github("richelbilderbeek/nLTT", ref = "develop")'
Rscript -e 'devtools::install_github("richelbilderbeek/pirouette", ref = "richel")'
Rscript -e 'devtools::install_github("Giappo/mbd")'
Rscript -e 'devtools::install_github("richelbilderbeek/becosys")'
Rscript -e 'devtools::install_github("richelbilderbeek/peregrine")'
Rscript -e 'devtools::install_github("richelbilderbeek/razzo", ref = "richel")'
Rscript -e 'devtools::install_github("richelbilderbeek/raket", ref = "richel")'
Rscript -e 'if (!beastier::is_beast2_installed()) beastier::install_beast2()'
Rscript -e 'if (!mauricer::is_beast2_pkg_installed("NS")) mauricer::install_beast2_pkg("NS")'
