#!/bin/bash
# Create input files
# Peregrine directives:
#SBATCH --time=100:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=create_input_files_sampling
#SBATCH --output=create_input_files_sampling.log
module load GCCcore/4.9.3 
module load XZ/5.2.2-foss-2016a
module load R
Rscript -e 'raket::create_input_files_sampling(sampling_params_set = raket::create_sampling_params_set(n_replicates = 10))'
