#!/bin/bash
# Script to create the raket input files
# on the Peregrine computer cluster.
#
# Usage, locally:
#
#   ./scripts/2_create_input_files_general
#
# Usage, on Peregrine:
#
#   sbatch ./scripts/2_create_input_files_general
#
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=2_create_input_files_general
#SBATCH --output=2_create_input_files_general.log
module load R
Rscript -e 'raket::create_input_files_general(general_params_set = raket::create_general_params_set(max_n_params = 4, mcmc_chain_length = 11000, n_replicates = 1, sequence_length = 1000))'
