#!/bin/bash
# Process all .RDa files
# Must be called from root folder
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=create_nltt_files
#SBATCH --output=create_nltt_files.log
for filename in $(find . | egrep ".*\.RDa")
do
  from=$filename
  to=`echo $from | sed 's/out_/nltt_/'`
  echo $from
  #echo $to
  # Must be called from root folder
  ./scripts/create_nltt_file $from $to
done
