#!/bin/bash
# Create input files
# Peregrine directives:
#SBATCH --time=10:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=to_long
#SBATCH --output=to_long.log
module load GCCcore/4.9.3 
module load XZ/5.2.2-foss-2016a
module load R
Rscript -e 'utils::write.csv(x = raket::to_long(), file = "result_long.csv", row.names = FALSE)'

