#!/bin/bash
# Process 1 RDA file
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=20G
#SBATCH --job-name=create_nltt_file
#SBATCH --output=create_nltt_file_%j.log
module load R
from=$1
to=$2
cmd="raket::create_nltt_file(\""$from"\",\""$to"\")"
echo $cmd
Rscript -e $cmd
