#!/bin/bash
# Process all .RDa files
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=create_nltt_files
#SBATCH --output=create_nltt_files.log
for filename in `ls out_*.RDa`
do
  from=$filename
  to=`echo $from | sed 's/out_/nltt_/'`
  #echo $from
  #echo $to
  sbatch ./create_nltt_file $from $to
done
