#!/bin/bash
# Process all .RDa files
# Peregrine directives:
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=process
#SBATCH --output=process.log
for filename in `ls *.RDa`
do
  echo $filename
  sbatch ./create_output_file $filename
done
