#!/bin/bash
# Process 1 RDA file
# Peregrine directives:
#SBATCH --time=240:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=20G
#SBATCH --job-name=create_posterior_files
#SBATCH --output=create_posterior_files_%j.log
#module load R/3.3.1-foss-2016a
module load R
from=$1
to=out_$1
cmd="raket::create_posterior_files(\""$from"\",\""$to"\")"
echo $cmd
Rscript -e $cmd
